### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by nouryehia** [MarkMa2003/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
   - should include link to VSCode
   - 
- [x] All relevant code examples written with backticks (```)
   - `ssh` commands should be in backticks
   - commands tried for step 3 should be in backticks
   - `scp` commands should be in backticks
   - `ssh-keygen` should be in backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
   - would recommend using headers for steps
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
   - not counting keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
- Nice theme!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by MarkMa2003** [comment]
what is meant by link to VSCode and written with backticks. Thanks in advance

**Comment by nouryehia** [comment]
For the link, you can include a link of the VSCode download page. For the backticks, in Markdown - commands are surrounded by the ` character
